# Run this in the 'source' directory
MODULES = decryptPostgres
OBJS = decryptPostgres.c	aes.c
EXTENSION = decryptPostgres
DATA = decryptPostgres--1.0.sql

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)