name: docs

on: [ push ]

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ethantimpe/aquacleanpro/build-docs:v1.0.2
      credentials:
        username: ethantimpe
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Spell Check
        run: codespell --write-changes

      - name: Build Docs
        run: |
          cd docs
          doxygen Doxyfile
          sphinx-build -M html . _html

      - name: Export HTML
        uses: actions/upload-artifact@v3
        with:
          name: aquaclean-pro-html
          path: docs/_html/html/*

      - name: Create CNAME file
        run: echo "docs.aquacleanpro.org" > docs/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_html/html
          force_orphan: true
          custom_domain: docs.aquacleanpro.org
