name: docs

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ethantimpe/aquacleanpro/build-docs:v1.0.2
      credentials:
        username: ethantimpe
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Spell Check
        run: codespell --write-changes

      - name: Build Docs
        run: |
          cd docs
          doxygen Doxyfile
          sphinx-build -M html . _html

      - name: Export HTML
        uses: actions/upload-artifact@v3
        # If not on main, export HTML build to zip
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          name: aquaclean-pro-html
          path: docs/_html/html/*

      - name: Create CNAME file
        run: echo "docs.aquacleanpro.org" > docs/CNAME

      - name: Update Custom Domain
        working-directory: ${{ github.workspace }}
        run: |
          git add docs/CNAME
          git commit -m "Update custom domain"
          git push origin HEAD:custom-domain-update

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: custom-domain-update
          destination_branch: main
          title: "Update Custom Domain"
          body: "Automated pull request to update custom domain."
