name: spell-check

on: [ push ]

jobs:
  spell-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ethantimpe/aquacleanpro/build-docs:v1.0.2
      credentials:
        username: ethantimpe
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Spell Check
        run: |
          codespell